"""canonical mysql schema

Revision ID: d7b5a45fd0fb
Revises: 
Create Date: 2026-08-24 08:52:44.914253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd7b5a45fd0fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('participant_target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('participant_target IS NULL OR participant_target >= 0', name='ck_events_participant_target_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('import_batches',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_slug', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('active_event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('validating','invalid','validated','processing','active','failed','superseded')", name='ck_import_batches_status'),
    sa.CheckConstraint("(status = 'active' AND active_event_id IS NOT NULL AND active_event_id = event_id) OR (status <> 'active' AND active_event_id IS NULL)", name='ck_import_batches_active_event'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_event_id', name='uq_import_batches_active_event'),
    sa.UniqueConstraint('event_id', 'id', name='uq_import_batches_event_id_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(
        'idx_import_batches_event',
        'import_batches',
        ['event_id', 'created_at'],
        unique=False,
    )
    op.create_table('buyers',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('event_slug', sa.String(length=255), nullable=True),
    sa.Column('buyer_reference', sa.String(length=255), nullable=False),
    sa.Column('payment_status', sa.String(length=96), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source_data_json', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'buyer_reference', name='uq_buyers_batch_reference'),
    sa.UniqueConstraint('batch_id', 'id', name='uq_buyers_batch_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_buyers_batch_status', 'buyers', ['batch_id', 'payment_status'], unique=False)
    op.create_table('curated_registrants',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Text(), nullable=True),
    sa.Column('birth_month', sa.String(length=32), nullable=True),
    sa.Column('birth_year', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('life_stage', sa.String(length=64), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('normalized_last_name', sa.String(length=255), nullable=True),
    sa.Column('normalized_birth_month', sa.String(length=8), nullable=True),
    sa.Column('normalized_birth_year', sa.String(length=8), nullable=True),
    sa.Column('normalized_gender', sa.String(length=32), nullable=True),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('dedupe_complete', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('dedupe_status', sa.String(length=24), nullable=False),
    sa.Column('missing_identity_fields', sa.String(length=255), nullable=True),
    sa.Column('registration_type', sa.String(length=24), nullable=False),
    sa.Column('registration_type_conflict', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('checked_in', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_registrant_count', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("dedupe_status IN ('complete','incomplete')", name='ck_curated_dedupe_status'),
    sa.CheckConstraint("registration_type IN ('participant','volunteer')", name='ck_curated_registration_type'),
    sa.CheckConstraint('dedupe_complete IN (0,1) AND registration_type_conflict IN (0,1) AND checked_in IN (0,1)', name='ck_curated_boolean_flags'),
    sa.CheckConstraint('source_registrant_count >= 1', name='ck_curated_source_count'),
    sa.ForeignKeyConstraint(['event_id', 'batch_id'], ['import_batches.event_id', 'import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'dedupe_key', name='uq_curated_batch_dedupe'),
    sa.UniqueConstraint('event_id', 'batch_id', 'id', name='uq_curated_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_curated_batch_type_checkin', 'curated_registrants', ['batch_id', 'registration_type', 'checked_in'], unique=False)
    op.create_index('idx_curated_event_batch', 'curated_registrants', ['event_id', 'batch_id'], unique=False)
    op.create_table('import_files',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('export_type', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('staged_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_rows', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('valid_rows', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('invalid_rows', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicate_records', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('relationship_issues', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('warning_count', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('detected_type', sa.String(length=24), nullable=True),
    sa.CheckConstraint("export_type IN ('tickets','buyers','registrants')", name='ck_import_files_export_type'),
    sa.CheckConstraint("status IN ('uploaded','validating','valid','invalid')", name='ck_import_files_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'export_type', name='uq_import_files_batch_export'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('registrants',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('event_slug', sa.String(length=255), nullable=True),
    sa.Column('registration_code', sa.String(length=255), nullable=False),
    sa.Column('ticket_code', sa.String(length=255), nullable=False),
    sa.Column('ticket_name_raw', sa.Text(), nullable=True),
    sa.Column('ticket_status', sa.String(length=96), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name_present', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_name_present', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_present', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('mobile_present', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('gender_raw', sa.String(length=255), nullable=True),
    sa.Column('life_stage_raw', sa.Text(), nullable=True),
    sa.Column('birth_date_raw', sa.Text(), nullable=True),
    sa.Column('birth_month_raw', sa.Text(), nullable=True),
    sa.Column('birth_year_raw', sa.Text(), nullable=True),
    sa.Column('b1g_satellite_hub_raw', sa.Text(), nullable=True),
    sa.Column('b1g_satellite_raw', sa.Text(), nullable=True),
    sa.Column('b1g_satellite_specify_raw', sa.Text(), nullable=True),
    sa.Column('attending_ccf_raw', sa.Text(), nullable=True),
    sa.Column('satellite_scope_raw', sa.Text(), nullable=True),
    sa.Column('local_satellite_raw', sa.Text(), nullable=True),
    sa.Column('international_satellite_raw', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.String(length=32), nullable=False),
    sa.Column('satellite_name', sa.String(length=512), nullable=True),
    sa.Column('registration_type', sa.String(length=24), server_default=sa.text("'participant'"), nullable=False),
    sa.Column('ticket_matched', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('checked_in', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_data_json', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.CheckConstraint("affiliation IN ('CCF Main','Local Satellite','International Satellite','Non-CCF','Unknown')", name='ck_registrants_affiliation'),
    sa.CheckConstraint("registration_type IN ('participant','volunteer')", name='ck_registrants_registration_type'),
    sa.CheckConstraint('first_name_present IN (0,1) AND last_name_present IN (0,1) AND email_present IN (0,1) AND mobile_present IN (0,1) AND ticket_matched IN (0,1) AND checked_in IN (0,1)', name='ck_registrants_boolean_flags'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'id', name='uq_registrants_batch_id'),
    sa.UniqueConstraint('batch_id', 'registration_code', name='uq_registrants_batch_registration'),
    sa.UniqueConstraint('batch_id', 'ticket_code', name='uq_registrants_batch_ticket'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_registrants_batch_affiliation', 'registrants', ['batch_id', 'ticket_matched', 'affiliation', 'checked_in'], unique=False)
    op.create_index('idx_registrants_batch_gender', 'registrants', ['batch_id', 'gender_raw'], unique=False)
    op.create_index('idx_registrants_batch_status', 'registrants', ['batch_id', 'ticket_status'], unique=False)
    op.create_index('idx_registrants_batch_type', 'registrants', ['batch_id', 'ticket_matched', 'registration_type'], unique=False)
    op.create_table('satellites',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('affiliation', sa.String(length=32), nullable=False),
    sa.Column('affiliation_conflict', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_record_count', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("affiliation IN ('CCF Main','Local Satellite','International Satellite')", name='ck_satellites_affiliation'),
    sa.CheckConstraint('affiliation_conflict IN (0,1)', name='ck_satellites_affiliation_conflict'),
    sa.CheckConstraint('source_record_count >= 0', name='ck_satellites_source_count'),
    sa.ForeignKeyConstraint(['event_id', 'batch_id'], ['import_batches.event_id', 'import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'normalized_name', name='uq_satellites_batch_name'),
    sa.UniqueConstraint('event_id', 'batch_id', 'id', name='uq_satellites_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_satellites_event_batch', 'satellites', ['event_id', 'batch_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('event_slug', sa.String(length=255), nullable=True),
    sa.Column('ticket_code', sa.String(length=255), nullable=False),
    sa.Column('control_number', sa.String(length=255), nullable=True),
    sa.Column('buyer_reference', sa.String(length=255), nullable=True),
    sa.Column('ticket_status', sa.String(length=96), nullable=True),
    sa.Column('payment_status', sa.String(length=96), nullable=True),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('source_data_json', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'id', name='uq_tickets_batch_id'),
    sa.UniqueConstraint('batch_id', 'ticket_code', name='uq_tickets_batch_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tickets_batch_buyer', 'tickets', ['batch_id', 'buyer_reference'], unique=False)
    op.create_index('idx_tickets_batch_checkin', 'tickets', ['batch_id', 'check_in_at'], unique=False)
    op.create_index('idx_tickets_batch_status', 'tickets', ['batch_id', 'ticket_status'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=96), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_identifier', sa.String(length=512), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.CheckConstraint("severity IN ('error','warning')", name='ck_validation_issues_severity'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_issues_batch_category', 'validation_issues', ['batch_id', 'category'], unique=False)
    op.create_table('curated_registrant_satellites',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('curated_registrant_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('satellite_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id', 'batch_id', 'curated_registrant_id'], ['curated_registrants.event_id', 'curated_registrants.batch_id', 'curated_registrants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id', 'batch_id', 'satellite_id'], ['satellites.event_id', 'satellites.batch_id', 'satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curated_registrant_id', 'satellite_id', name='uq_curated_satellites_pair'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_curated_satellites_batch', 'curated_registrant_satellites', ['batch_id'], unique=False)
    op.create_index('idx_curated_satellites_curated', 'curated_registrant_satellites', ['curated_registrant_id'], unique=False)
    op.create_index('idx_curated_satellites_satellite', 'curated_registrant_satellites', ['satellite_id'], unique=False)
    op.create_table('curated_registrant_sources',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('curated_registrant_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('registrant_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id', 'registrant_id'], ['registrants.batch_id', 'registrants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id', 'batch_id', 'curated_registrant_id'], ['curated_registrants.event_id', 'curated_registrants.batch_id', 'curated_registrants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'registrant_id', name='uq_curated_sources_batch_registrant'),
    sa.UniqueConstraint('curated_registrant_id', 'registrant_id', name='uq_curated_sources_pair'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_curated_sources_batch', 'curated_registrant_sources', ['batch_id'], unique=False)
    op.create_index('idx_curated_sources_curated', 'curated_registrant_sources', ['curated_registrant_id'], unique=False)
    op.create_index('idx_curated_sources_registrant', 'curated_registrant_sources', ['registrant_id'], unique=False)
    op.create_table('satellite_source_variations',
    sa.Column('id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('satellite_id', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_value', sa.String(length=512, collation='utf8mb4_bin'), nullable=False),
    sa.Column('normalized_source_value', sa.String(length=512), nullable=False),
    sa.Column('affiliation', sa.String(length=32), nullable=False),
    sa.Column('source_record_count', mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("affiliation IN ('CCF Main','Local Satellite','International Satellite')", name='ck_variations_affiliation'),
    sa.CheckConstraint('source_record_count >= 0', name='ck_variations_source_count'),
    sa.ForeignKeyConstraint(['event_id', 'batch_id', 'satellite_id'], ['satellites.event_id', 'satellites.batch_id', 'satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'source_value', 'affiliation', name='uq_variations_source'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_satellite_variations_satellite', 'satellite_source_variations', ['satellite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_satellite_variations_satellite', table_name='satellite_source_variations')
    op.drop_table('satellite_source_variations')
    op.drop_index('idx_curated_sources_registrant', table_name='curated_registrant_sources')
    op.drop_index('idx_curated_sources_curated', table_name='curated_registrant_sources')
    op.drop_index('idx_curated_sources_batch', table_name='curated_registrant_sources')
    op.drop_table('curated_registrant_sources')
    op.drop_index('idx_curated_satellites_satellite', table_name='curated_registrant_satellites')
    op.drop_index('idx_curated_satellites_curated', table_name='curated_registrant_satellites')
    op.drop_index('idx_curated_satellites_batch', table_name='curated_registrant_satellites')
    op.drop_table('curated_registrant_satellites')
    op.drop_index('idx_issues_batch_category', table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index('idx_tickets_batch_status', table_name='tickets')
    op.drop_index('idx_tickets_batch_checkin', table_name='tickets')
    op.drop_index('idx_tickets_batch_buyer', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_satellites_event_batch', table_name='satellites')
    op.drop_table('satellites')
    op.drop_index('idx_registrants_batch_type', table_name='registrants')
    op.drop_index('idx_registrants_batch_status', table_name='registrants')
    op.drop_index('idx_registrants_batch_gender', table_name='registrants')
    op.drop_index('idx_registrants_batch_affiliation', table_name='registrants')
    op.drop_table('registrants')
    op.drop_table('import_files')
    op.drop_index('idx_curated_event_batch', table_name='curated_registrants')
    op.drop_index('idx_curated_batch_type_checkin', table_name='curated_registrants')
    op.drop_table('curated_registrants')
    op.drop_index('idx_buyers_batch_status', table_name='buyers')
    op.drop_table('buyers')
    op.drop_index('idx_import_batches_event', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('events')
    # ### end Alembic commands ###
